AWSTemplateFormatVersion: 2010-09-09
Description: "Aurora-Cluster-Sample"
Parameters:
  DBName:
    Default: TestProject
    Description: The database name
    Type: String
    MinLength: '1'
    MaxLength: '64'
    AllowedPattern: '[a-zA-Z][a-zA-Z0-9]*'
    ConstraintDescription: must begin with a letter and contain only alphanumeric characters.
  DBUser:
    NoEcho: 'true'
    Default: burgess
    Description: The database admin account username
    Type: String
    MinLength: '1'
    MaxLength: '16'
    AllowedPattern: '[a-zA-Z][a-zA-Z0-9]*'
    ConstraintDescription: must begin with a letter and contain only alphanumeric characters.
  DBPassword:
    NoEcho: 'true'
    Default: burgess1109
    Description: The database admin account password
    Type: String
    MinLength: '8'
    MaxLength: '41'
    AllowedPattern: '[a-zA-Z0-9]+'
    ConstraintDescription: must contain only alphanumeric characters.
  EC2SecurityGroup:
    Description: The EC2 security group that contains instances that need access to the database
    Default: default
    Type: String
    AllowedPattern: '[a-zA-Z0-9\-]+'
    ConstraintDescription: must be a valid security group name.
Resources:
  DBEC2SecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupName: Aurora-cluster-access-test
      GroupDescription: Open database for access
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '3306'
          ToPort: '3306'
          # CidrIp: 0.0.0.0/0
          SourceSecurityGroupName: !Ref EC2SecurityGroup
  DBCluster:
    Type: 'AWS::RDS::DBCluster'
    Properties:
      DatabaseName: !Ref DBName
      DBClusterIdentifier: DB-Cluster-Test
      Engine: aurora
      MasterUsername: !Ref DBUser
      MasterUserPassword: !Ref DBPassword
      Port: 3306
      Tags:
        - Key: Name
          Value: Master Cluster
      VpcSecurityGroupIds:
        - !GetAtt DBEC2SecurityGroup.GroupId
  MasterDB:
    Type: 'AWS::RDS::DBInstance'
    Properties:
      Engine: aurora
      DBClusterIdentifier: !Ref DBCluster
      DBInstanceClass: db.t2.small
      DBInstanceIdentifier: DB-Test
      PubliclyAccessible: true
      Tags:
        - Key: Name
          Value: Master Database
  ReplicaDB:
    Type: 'AWS::RDS::DBInstance'
    Properties:
      Engine: aurora
      DBClusterIdentifier: !Ref DBCluster
      DBInstanceClass: db.t2.small
      DBInstanceIdentifier: DB-Test-Replica
      PubliclyAccessible: true
      Tags:
        - Key: Name
          Value: Read Replica Database

Outputs:
  MasterJDBCConnectionString:
    Description: JDBC connection string for the master database
    Value: !Join
      - ''
      - - 'jdbc:mysql://'
        - !GetAtt
          - MasterDB
          - Endpoint.Address
        - ':'
        - !GetAtt
          - MasterDB
          - Endpoint.Port
        - /
        - !Ref DBName
  ReplicaJDBCConnectionString:
    Description: JDBC connection string for the replica database
    Value: !Join
      - ''
      - - 'jdbc:mysql://'
        - !GetAtt
          - ReplicaDB
          - Endpoint.Address
        - ':'
        - !GetAtt
          - ReplicaDB
          - Endpoint.Port
        - /
        - !Ref DBName
