AWSTemplateFormatVersion: 2010-09-09
Description: 'DynamoDB-Sample'
Parameters:
  TableName:
    Default: Album
    Description: The table name
    Type: String
    MinLength: '1'
    MaxLength: '64'
    AllowedPattern: '[a-zA-Z0-9_.-]+'
    ConstraintDescription: must contain only alphanumeric characters.
Resources:
  DynamoDBUserTable:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      TableName: !Ref TableName
      AttributeDefinitions:
        - AttributeName: Album
          AttributeType: S
        - AttributeName: Artist
          AttributeType: S
        - AttributeName: Sales
          AttributeType: N
      KeySchema:
        - AttributeName: Album
          KeyType: HASH
        - AttributeName: Artist
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      GlobalSecondaryIndexes:
        - IndexName: Sales-Artist-Index
          KeySchema:
            - AttributeName: Sales
              KeyType: HASH
            - AttributeName: Artist
              KeyType: RANGE
          Projection:
            NonKeyAttributes:
              - Album
            ProjectionType: INCLUDE
          ProvisionedThroughput:
            ReadCapacityUnits: 5
            WriteCapacityUnits: 5
      LocalSecondaryIndexes:
        - IndexName: Album-Sales-Index
          KeySchema:
            - AttributeName: Album
              KeyType: HASH
            - AttributeName: Sales
              KeyType: RANGE
          Projection:
            NonKeyAttributes:
              - Artist
            ProjectionType: INCLUDE

Outputs:
  InstanceId:
    Description: InstanceId of the newly created DynamoDB instance
    Value: !Ref DynamoDBUserTable
